# Lab 7 - TensorFlow

Tensors

In [3]:
pip install --upgrade pip

  Using cached pip-24.0-py3-none-any.whl (2.1 MB)
  Attempting uninstall: pip
    Found existing installation: pip 22.3.1
    Uninstalling pip-22.3.1:
      Successfully uninstalled pip-22.3.1
Note: you may need to restart the kernel to use updated packages.


In [4]:
pip install tensorflow


  Using cached gast-0.5.4-py3-none-any.whl.metadata (1.3 kB)
  Using cached termcolor-2.4.0-py3-none-any.whl.metadata (6.1 kB)
     ---------------------------------------- 0.0/46.2 kB ? eta -:--:--
     ---------------------------------------- 46.2/46.2 kB 1.2 MB/s eta 0:00:00
   ---------------------------------------- 0.0/376.9 MB ? eta -:--:--
   ---------------------------------------- 0.5/376.9 MB 15.9 MB/s eta 0:00:24
   ---------------------------------------- 2.7/376.9 MB 29.0 MB/s eta 0:00:13
    --------------------------------------- 5.2/376.9 MB 37.1 MB/s eta 0:00:11
    --------------------------------------- 7.9/376.9 MB 46.1 MB/s eta 0:00:08
   - -------------------------------------- 10.3/376.9 MB 46.7 MB/s eta 0:00:08
   - -------------------------------------- 12.0/376.9 MB 54.7 MB/s eta 0:00:07
   - -------------------------------------- 15.2/376.9 MB 59.5 MB/s eta 0:00:07
   - -------------------------------------- 17.2/376.9 MB 46.7 MB/s eta 0:00:08
   - --------

In [7]:
import tensorflow as tf

# Create a tensor
tensor = tf.constant([[1, 2], [3, 4]])
print(tensor)

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


In [8]:
# Addition
tensor_add = tensor + 5
print(tensor_add)

# Multiplication
tensor_mul = tensor * 2
print(tensor_mul)

tf.Tensor(
[[6 7]
 [8 9]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[2 4]
 [6 8]], shape=(2, 2), dtype=int32)


Building a Simple Model

In [9]:
# Define a simple Sequential model
model = tf.keras.Sequential([
    tf.keras.layers.Dense(10, activation='relu', input_shape=(None, 5)),
    tf.keras.layers.Dense(1)
])

model.summary()

model.compile(optimizer='adam', loss='mean_squared_error')

C:\Users\14373\anaconda3\lib\site-packages\keras\src\layers\core\dense.py:88: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, None, 10)       │            60 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, None, 1)        │            11 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 71 (284.00 B)

 Trainable params: 71 (284.00 B)

 Non-trainable params: 0 (0.00 B)

1. Layer Types in Keras Documentation:

Keras provides various types of layers, each serving different purposes in building neural networks. Some common layer types include:
Dense Layer: A fully connected layer where each neuron is connected to every neuron in the previous layer. It is one of the basic building blocks of a neural network. The Dense layer performs a linear operation followed by an activation function (like ReLU, sigmoid, etc.). It takes an input tensor and outputs a tensor where every input is connected to every output by a weight.

2. model.summary() Output:

The model.summary() function provides a summary of the model architecture, including the type of layers, their output shapes, and the number of parameters in each layer.
For each layer, it shows:
Layer type.
Output shape (including batch size if specified as None).
Number of parameters (trainable and non-trainable).

3. model.compile():

model.compile() is used to configure the learning process before training the model. It specifies the optimizer, loss function, and optional metrics to be used during training.
Syntax: compile(optimizer, loss, metrics=None, loss_weights=None, weighted_metrics=None, run_eagerly=None, steps_per_execution=None)
Parameters:
optimizer: Specifies the optimizer algorithm to use during training (e.g., 'adam', 'sgd', etc.).
loss: Specifies the loss function to use for optimizing the model.
metrics (optional): Specifies the metrics to evaluate the model's performance during training and testing.

4. Optimizer:

An optimizer is a specific algorithm used to update the weights and biases of a neural network during training in order to minimize the loss function.
It adjusts the parameters of the model in the direction that reduces the loss, typically using techniques like gradient descent and its variants.
Common optimizers include Adam, SGD (Stochastic Gradient Descent), RMSprop, etc.

5. Loss:

Loss is a measure of how well the model is performing on the given data.
It quantifies the difference between the predicted output and the actual output.
During training, the goal is to minimize this loss function, which guides the optimizer in adjusting the model's parameters.
Examples of loss functions include Mean Squared Error (MSE) for regression tasks, Binary Cross-Entropy for binary classification, and Categorical Cross-Entropy for multi-class classification.

## Implement a Simple TensorFlow Example

### Generate Data

In [12]:
import numpy as np

# Generate random data
inputs = np.random.random((1000, 2))
sums = np.sum(inputs, axis=1, keepdims=True)

print(inputs[:5], sums[:5])

[[0.13152201 0.76793763]
 [0.09992977 0.29046558]
 [0.19977851 0.91122585]
 [0.46205876 0.70416237]
 [0.72522056 0.83495711]] [[0.89945965]
 [0.39039534]
 [1.11100436]
 [1.16622112]
 [1.56017767]]


### Build a Model

In [18]:
import tensorflow as tf

# Define the model architecture
model = tf.keras.Sequential([
    tf.keras.layers.Dense(64, activation='relu', input_shape=(10,)),  # Assuming 10 features per sample
    tf.keras.layers.Dense(1)  
])


# Compile the model with specified optimizer and loss function
model.compile(optimizer='adam', loss='mean_squared_error')

### Train the Model

In [19]:
import numpy as np

# Assuming X_train and y_train are your training data
num_samples = 1000
num_features = 10

X_train = np.random.random((num_samples, num_features))
y_train = np.random.random((num_samples, 1))  # Assuming you have single-value targets, adjust the shape if needed

# Train the model
model.fit(X_train, y_train, epochs=10, batch_size=32)


Epoch 1/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.1401   
Epoch 2/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 835us/step - loss: 0.0906
Epoch 3/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 798us/step - loss: 0.0930
Epoch 4/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 741us/step - loss: 0.0894
Epoch 5/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 810us/step - loss: 0.0872
Epoch 6/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 824us/step - loss: 0.0881
Epoch 7/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 738us/step - loss: 0.0849
Epoch 8/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 712us/step - loss: 0.0819
Epoch 9/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 819us/step - loss: 0.0812
Epoch 10/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 774us/step - loss: 0.0811


### Test the Model

In [21]:
# Test data
test_data = np.array([[1, 2, 3, 4, 5, 6, 7, 8, 9, 10], [4, 5, 6, 7, 8, 9, 10, 11, 12, 13]])

# Prediction
predictions = model.predict(test_data)

# Show Predictions
print(predictions)


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step
[[3.6284187]
 [5.1373672]]
